$arrayProductos = array(
('Aceite','Aceites y grasas'),
('Aceite de oliva','Aceites y grasas'),
('Grasa comestible','Aceites y grasas'),
('Manteca','Aceites y grasas'),
('Manteca de cerdo','Aceites y grasas'),
('Margarina','Aceites y grasas'),
('Minarina','Aceites y grasas'),
('Agua con gas','Bebidas'),
('Agua sin gas','Bebidas'),
('Bebida hidratante','Bebidas'),
('Jugo de fruta','Bebidas'),
('Refresco','Bebidas'),
('Cerveza','Bebidas'),
('Jerez','Bebidas'),
('Rompope','Bebidas'),
('Sidra','Bebidas'),
('Vino de mesa','Bebidas'),
('Azúcar','Café, endulzantes y saborizantes'),
('Café soluble','Café, endulzantes y saborizantes'),
('Café tostado y molido','Café, endulzantes y saborizantes'),
('Jarabe p/preparar bebidas','Café, endulzantes y saborizantes'),
('Miel de abeja','Café, endulzantes y saborizantes'),
('Piloncillo','Café, endulzantes y saborizantes'),
('Polvo p/preparar bebidas','Café, endulzantes y saborizantes'),
('Te','Café, endulzantes y saborizantes'),
('Bistec de diezmillo de res','Carnes'),
('Bistec de espaldilla de res','Carnes'),
('Chuleta de res','Carnes'),
('Falda de res','Carnes'),
('Filete de res','Carnes'),
('Hígado de res','Carnes'),
('Milanesa de res','Carnes'),
('Panza de res','Carnes'),
('Res','Carnes'),
('Retazo hueso de res','Carnes'),
('Ternera','Carnes'),
('Cabeza de cerdo','Carnes'),
('Carnes molida de cerdo','Carnes'),
('Carnes molida de res','Carnes'),
('Cerdo','Carnes'),
('Chuleta ahumada de cerdo','Carnes'),
('Espinazo de cerdo','Carnes'),
('Lomo de cerdo','Carnes'),
('Milanesa de cerdo','Carnes'),
('Pata de cerdo','Carnes'),
('Pierna ce cerdo entera/ pernil','Carnes'),
('Pavo','Carnes'),
('Pechuga de pollo','Carnes'),
('Pierna de pollo','Carnes'),
('Pollo','Carnes'),
('Pollo entero','Carnes'),
('Arroz','Cereales'),
('Avena','Cereales'),
('Cereal mixto','Cereales'),
('Harina de arroz','Cereales'),
('Otros cereales','Cereales'),
('Ajonjolí','Condimentos y aderezos'),
('Canela','Condimentos y aderezos'),
('Chilorio','Condimentos y aderezos'),
('Clavo','Condimentos y aderezos'),
('Cochinita pibil','Condimentos y aderezos'),
('Concentrado de pollo','Condimentos y aderezos'),
('Condimento de achiote','Condimentos y aderezos'),
('Hojas de perejil','Condimentos y aderezos'),
('Mayonesa','Condimentos y aderezos'),
('Mole rojo en pasta','Condimentos y aderezos'),
('Mostaza','Condimentos y aderezos'),
('Pimienta','Condimentos y aderezos'),
('Polvo p/hornear','Condimentos y aderezos'),
('Sal','Condimentos y aderezos'),
('Sal molida de mesa','Condimentos y aderezos'),
('Salsa','Condimentos y aderezos'),
('Salsa catsup','Condimentos y aderezos'),
('Salsa de chile','Condimentos y aderezos'),
('Salsa de soya','Condimentos y aderezos'),
('Salsa inglesa','Condimentos y aderezos'),
('Salsa mexicana','Condimentos y aderezos'),
('Salsa picante','Condimentos y aderezos'),
('Sopa y crema','Condimentos y aderezos'),
('Vainilla','Condimentos y aderezos'),
('Vinagre','Condimentos y aderezos'),
('Cajeta','Dulces y golosinas'),
('Chocolate en tablillas','Dulces y golosinas'),
('Colación','Dulces y golosinas'),
('Flan','Dulces y golosinas'),
('Gelatina en polvo','Dulces y golosinas'),
('Peladillas','Dulces y golosinas'),
('Polvo bebida sabor chocolate','Dulces y golosinas'),
('Polvorón','Dulces y golosinas'),
('Postre estilo flan','Dulces y golosinas'),
('Praline','Dulces y golosinas'),
('Torta Imperial','Dulces y golosinas'),
('Turrón','Dulces y golosinas'),
('Chile','Legumbres secas'),
('Chile seco','Legumbres secas'),
('Frijol','Legumbres secas'),
('Garbanza','Legumbres secas'),
('Haba','Legumbres secas'),
('Lenteja','Legumbres secas'),
('Bolillo','Pan y derivados del trigo'),
('Cereales','Pan y derivados del trigo'),
('Galletas','Pan y derivados del trigo'),
('Galletas dulces','Pan y derivados del trigo'),
('Galletas populares','Pan y derivados del trigo'),
('Harina de trigo','Pan y derivados del trigo'),
('Harina hot cakes','Pan y derivados del trigo'),
('Pan de caja','Pan y derivados del trigo'),
('Pan tostado','Pan y derivados del trigo'),
('Pasta para sopa','Pan y derivados del trigo'),
('Pastelillos','Pan y derivados del trigo'),
('Tortilla de harina de trigo','Pan y derivados del trigo'),
('Almeja','Pescados y mariscos'),
('Atún','Pescados y mariscos'),
('Bacalao','Pescados y mariscos'),
('Blanco Nilo','Pescados y mariscos'),
('Boquerón','Pescados y mariscos'),
('Calamar','Pescados y mariscos'),
('Callo de hacha','Pescados y mariscos'),
('Camarón','Pescados y mariscos'),
('Carpa','Pescados y mariscos'),
('Cazón','Pescados y mariscos'),
('Charal','Pescados y mariscos'),
('Cintilla','Pescados y mariscos'),
('Curvina','Pescados y mariscos'),
('Gurrubata','Pescados y mariscos'),
('Huachinango','Pescados y mariscos'),
('Jaiba','Pescados y mariscos'),
('Langosta','Pescados y mariscos'),
('Langostino','Pescados y mariscos'),
('Lenguado','Pescados y mariscos'),
('Lisa','Pescados y mariscos'),
('Lobina','Pescados y mariscos'),
('Mero','Pescados y mariscos'),
('Mojarra','Pescados y mariscos'),
('Pámpano','Pescados y mariscos'),
('Pescado seco salado','Pescados y mariscos'),
('Pulpo','Pescados y mariscos'),
('Robalo','Pescados y mariscos'),
('Salmón','Pescados y mariscos'),
('Sardina','Pescados y mariscos'),
('Sierra','Pescados y mariscos'),
('Trucha','Pescados y mariscos'),
('Villajaiba','Pescados y mariscos'),
('Acelga','Frutas y verduras'),
('Aguacate','Frutas y verduras'),
('Ajo','Frutas y verduras'),
('Alcachofa','Frutas y verduras'),
('Alcaparra','Frutas y verduras'),
('Almendras','Frutas y verduras'),
('Apio','Frutas y verduras'),
('Avellana','Frutas y verduras'),
('Betabel','Frutas y verduras'),
('Brócoli','Frutas y verduras'),
('Cacahuates','Frutas y verduras'),
('Calabaza','Frutas y verduras'),
('Caña','Frutas y verduras'),
('Castañas','Frutas y verduras'),
('Cebolla','Frutas y verduras'),
('Champiñón','Frutas y verduras'),
('Chayote','Frutas y verduras'),
('Chícharos','Frutas y verduras'),
('Chile fresco','Frutas y verduras'),
('Chiles','Frutas y verduras'),
('Chiles gueros','Frutas y verduras'),
('Ciruela','Frutas y verduras'),
('Ciruela pasa','Frutas y verduras'),
('Col','Frutas y verduras'),
('Coliflor','Frutas y verduras'),
('Dátil','Frutas y verduras'),
('Durazno','Frutas y verduras'),
('Ejote','Frutas y verduras'),
('Elote','Frutas y verduras'),
('Espinacas','Frutas y verduras'),
('Fresa','Frutas y verduras'),
('Frijoles','Frutas y verduras'),
('Frutas cubiertas','Frutas y verduras'),
('Granada','Frutas y verduras'),
('Guanábana','Frutas y verduras'),
('Guayaba','Frutas y verduras'),
('Jamaica','Frutas y verduras'),
('Jícama','Frutas y verduras'),
('Jitomate','Frutas y verduras'),
('Kiwi','Frutas y verduras'),
('Lechuga','Frutas y verduras'),
('Lima','Frutas y verduras'),
('Limón','Frutas y verduras'),
('Mamey','Frutas y verduras'),
('Mandarina','Frutas y verduras'),
('Mango','Frutas y verduras'),
('Manzana','Frutas y verduras'),
('Melón','Frutas y verduras'),
('Naranja','Frutas y verduras'),
('Nopal','Frutas y verduras'),
('Nopalitos','Frutas y verduras'),
('Nuez','Frutas y verduras'),
('Orejón','Frutas y verduras'),
('Papa','Frutas y verduras'),
('Papaya','Frutas y verduras'),
('Pasa (Uva pasa)','Frutas y verduras'),
('Pepino','Frutas y verduras'),
('Pera','Frutas y verduras'),
('Pimiento','Frutas y verduras'),
('Piña','Frutas y verduras'),
('Plátano','Frutas y verduras'),
('Rábano','Frutas y verduras'),
('Romeritos','Frutas y verduras'),
('Sandía','Frutas y verduras'),
('Tamarindo','Frutas y verduras'),
('Tejocote','Frutas y verduras'),
('Tomate','Frutas y verduras'),
('Toronja','Frutas y verduras'),
('Tuna','Frutas y verduras'),
('Uva','Frutas y verduras'),
('Verdolaga','Frutas y verduras'),
('Zanahoria','Frutas y verduras'),
('Aceituna','Alimentos procesados'),
('Aceituna manzanilla','Alimentos procesados'),
('Aceituna rellena con pimiento','Alimentos procesados'),
('Alimento preparado p/niños','Alimentos procesados'),
('Chícharos en lata','Alimentos procesados'),
('Chiles en lata','Alimentos procesados'),
('Chiles largos en escabeche','Alimentos procesados'),
('Coctel de frutas en almíbar','Alimentos procesados'),
('Duraznos en almíbar','Alimentos procesados'),
('Hortalizas congeladas','Alimentos procesados'),
('Mango en almíbar','Alimentos procesados'),
('Mermelada','Alimentos procesados'),
('Pera en almíbar','Alimentos procesados'),
('Piña en almíbar','Alimentos procesados'),
('Puré de tomate','Alimentos procesados'),
('Huevo','Lácteos y huevo'),
('Crema','Lácteos y huevo'),
('Crema batida','Lácteos y huevo'),
('Mantequilla','Lácteos y huevo'),
('Queso canasto','Lácteos y huevo'),
('Queso chihuahua','Lácteos y huevo'),
('Queso cotija','Lácteos y huevo'),
('Queso doble crema','Lácteos y huevo'),
('Queso manchego','Lácteos y huevo'),
('Queso panela','Lácteos y huevo'),
('Queso sierra','Lácteos y huevo'),
('Yoghurt','Lácteos y huevo'),
('Fórmula láctea','Lácteos y huevo'),
('Leche condensada','Lácteos y huevo'),
('Leche en polvo','Lácteos y huevo'),
('Leche evaporada','Lácteos y huevo'),
('Leche pasteurizada','Lácteos y huevo'),
('Leche ultrapasteurizada','Lácteos y huevo'),
('Chorizo','Salchichonería'),
('Jamón','Salchichonería'),
('jamòn de pavo','Salchichonería'),
('Longaniza','Salchichonería'),
('Mortadela','Salchichonería'),
('Pastel pimiento','Salchichonería'),
('Paté','Salchichonería'),
('Queso de puerco','Salchichonería'),
('Salami','Salchichonería'),
('Salchicha','Salchichonería'),
('Tocino','Salchichonería'),
('Harina de maíz','Tortillas y maíz'),
('Maíz pozolero','Tortillas y maíz'),
('Tortilla de maíz','Tortillas y maíz'),
('Foco','Varios'),
('Pilas eléctricas','Varios'),
('Acondicionador / enjuague','Cuidado personal'),
('Champú','Cuidado personal'),
('Champú para bebés','Cuidado personal'),
('Crema dental','Cuidado personal'),
('Crema líquida','Cuidado personal'),
('Crema sólida','Cuidado personal'),
('Desodorante','Cuidado personal'),
('Jabon de tocador','Cuidado personal'),
('Pañales desechables','Cuidado personal'),
('Papel higiénico','Cuidado personal'),
('Rastrillos desechables','Cuidado personal'),
('Repuestos de navajas','Cuidado personal'),
('Tinte para el cabello','Cuidado personal'),
('Toalla femenina','Cuidado personal'),
('Toallita húmeda limpiadora','Cuidado personal'),
('Acondicionador de telas','Limpieza del hogar'),
('Barra limpiadora','Limpieza del hogar'),
('Blanqueador','Limpieza del hogar'),
('Detergente ropa','Limpieza del hogar'),
('Detergente ropa líquido','Limpieza del hogar'),
('Detergente ropa polvo','Limpieza del hogar'),
('Detergente trastes','Limpieza del hogar'),
('Insecticida aerosol','Limpieza del hogar'),
('Jabón de pasta','Limpieza del hogar'),
('Jabón limpiador','Limpieza del hogar'),
('Limpiador líquido','Limpieza del hogar'),
('Limpiador lìquido piso','Limpieza del hogar'),
('Servilletas de papel','Limpieza del hogar'),
('Suavizante ropa','Limpieza del hogar'),
('Toalla de papel','Limpieza del hogar')
);